return {
  -- "olimorris/codecompanion.nvim",
  -- dependencies = {
  --   "lalitmee/codecompanion-spinners.nvim",
  --   "j-hui/fidget.nvim",
  --   "xinghe98/codecompanion-model-selector.nvim",
  -- },
  -- init = function()
  --   require("plugins.codecompanion.keymaps")
  -- end,
  -- opts = {
  --   extensions = require("plugins.codecompanion.extensions"),
  --   language = "zh-CN",
  --   strategies = require("plugins.codecompanion.strategies"),
  --   prompt_library = require("plugins.codecompanion.prompts"),
  --   display = {
  --     diff = {
  --       enabled = true,
  --
  --       -- At or below this diff size, always display the diff in the chat buffer
  --       threshold_for_chat = 6,
  --
  --       word_highlights = {
  --         additions = true,
  --         deletions = true,
  --       },
  --     },
  --   },
  --   rules = {
  --     default = {
  --       description = "Collection of common files for all projects",
  --       files = {
  --         "AGENT.md",
  --         "AGENTS.md",
  --       },
  --       is_preset = true,
  --     },
  --     opts = {
  --       chat = {
  --         autoload = "default", -- The rule groups to load
  --         enabled = true,
  --       },
  --     },
  --   },
  -- },
}
