local set = vim.opt
set.number=true
set.rnu=true
set.wrap=false
set.fileformat=unix
set.cindent=true
set.tabstop=4
set.shiftwidth=4
set.showmatch=true
set.scrolloff=5
set.laststatus=2
set.fenc='utf-8'
vim.g.mapleader=" "
set.matchtime=5
set.ignorecase=true
set.incsearch=true
set.hlsearch=true
set.expandtab=false
set.autoread=true
vim.g.t_Co=256
