return {
  -- {
  --   "pmizio/typescript-tools.nvim",
  --   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  --   build = "yarn add global @vue/typescript-plugin",
  --   opts = {
  --     filetypes = {
  --       "javascript",
  --       "javascriptreact",
  --       "typescript",
  --       "typescriptreact",
  --     },
  --     settings = {
  --       expose_as_code_action = {
  --         "add_missing_imports",
  --         "remove_unused",
  --         "remove_unused_imports",
  --         "organize_imports",
  --         "fix_all",
  --       },
  --       tsserver_plugins = {
  --         "@vue/typescript-plugin",
  --         "@styled/typescript-styled-plugin",
  --       },
  --       tsserver_locale = "zh-CN",
  --       tsserver_file_preferences = {
  --         includeInlayParameterNameHints = "all",
  --         includeCompletionsForModuleExports = true,
  --         quotePreference = "auto",
  --         includeInlayParameterNameHintsWhenArgumentMatchesName = true,
  --         includeInlayFunctionParameterTypeHints = true,
  --         includeInlayVariableTypeHints = true,
  --         includeInlayVariableTypeHintsWhenTypeMatchesName = true,
  --         includeInlayPropertyDeclarationTypeHints = true,
  --         includeInlayFunctionLikeReturnTypeHints = true,
  --         includeInlayEnumMemberValueHints = true,
  --       },
  --     },
  --   },
  -- },
}
